### ISSUE TITLE
Money Parsing?

### ISSUE THREAD

**Issue by carcinocron** [gerardojbaez/money#1]
Any plans for parsing the outputs of moneyFormat?

**Comment by gerardojbaez** [comment]
What do you mean by 'parsing the outputs' of moneyFormat?

**Comment by carcinocron** [comment]
Basically the opposite of this library's current feature:

```
use Gerardojbaez\Money\Money;

$formatted_value = moneyFormat('1234567.89', 'USD'); // RESULT: '$1,234,567.89'
$parsed_value = moneyParse('$1,234,567.89', 'USD');  // RESULT: '1234567.89'

$money = Money::parse('$1,234,567.89', 'USD'); // RESULT: Gerardojbaez\Money\Money {#1867}
$money->amount(); // RESULT: '1234567.89'
```

**Comment by gerardojbaez** [comment]
That's a good feature to have. Currently I'm working on correcting the currencies data; if you want, you can implement it and make a pull request. 

I think something like this will do the trick: 

``` php
// Replace everything that isn't a number or a dot.
preg_replace("/[^\.\d]/", "", '$1,234,567.89');
// '1234567.89'
```

What do you think?

**Comment by carcinocron** [comment]
What is the goal of this library? I like it because:
- the API fits my use case better than some of the others (and is cleaner, less "global").
- Seems like a clear upgrade path to using the same logic in the clientside JS is possible and simple.
- Does not use `setLocale`.
- I feel like I can add custom currencies easier than php-7.0intl seems.

**Comment by gerardojbaez** [comment]
I've created this library for a project that I'm working on. I was looking for a library easy to use and easy to configure from a database, since the project I'm working on will be listed on codecanyon.com, I don't want to hard code the currency or worst, show plain prices numbers. I had tried find a library but none of them met my requirements, so I opted to create it myself.

In short, the goals of this library are:
- Easy to use and to extend (I plan to add a feature were you'll have the ability to override or add currencies)
- Cross-platform
