### ISSUE TITLE
Source for Currency data?

### ISSUE THREAD

**Issue by carcinocron** [gerardojbaez/money#4]
I have a user that claims "EURO symbol should be on the left side of the numbers" and provided a source for it: http://ux.stackexchange.com/questions/9105/international-currency-formatting-guidelines-currency-codes

I was wondering:
- if there was a data source for the current currency data.
- if the `symbolPlacement` claim should be fixed or refuted.

**Comment by gerardojbaez** [comment]
The placement of the symbols depends on the language rather on the currency. For example, in english the Euro symbol is placed before the value while in many other European languages is placed after.

All currencies were validated against some trusted sources like Wikipedia, thefinancials.com and cldr.unicode.org. Each format used on each currency is the format used in the country of procedence of the currency and under the "main language" for that country. When this information isn't found, the English format under that country is used.

In our code, we have placed the symbol after the value based on the locale `es-ES`. 

In php if you use `NumberFormatter`, using the same configuration (EUR/es-ES) you will get the same result: `13.00 €`. 

The placement of each symbol is debatable. I plan to add a function where the user can override the default format when needed. This is perfect when you are working on a multilanguage app since you can add the formats to each language file.

Should we go for a "more general format" and place it in the left side?

**Comment by carcinocron** [comment]
Right now I'm leaning on changing nothing about the default data source, but letting my users override the default currency settings as they see fit.

**Comment by gerardojbaez** [comment]
That's a good option.
