### ISSUE TITLE
Do not store money as a float.

### ISSUE THREAD

**Issue by wrossmann** [gerardojbaez/money#7]
Avoiding this is usually the _entire_ reason for a money library.

https://github.com/gerardojbaez/money/blob/388f7cc506de58667644795130ca3c196fc36ec6/src/Money.php#L30

**Comment by carcinocron** [comment]
This is a library for formating currencies. This isn't a math library. No floating point math is performed. `number_format` accepts float as the first parameter:
```
string number_format ( float $number , int $decimals = 0 , string $dec_point = "." , string $thousands_sep = "," )
```

http://php.net/manual/en/function.number-format.php

**Comment by gerardojbaez** [comment]
@InstanceOfMichael is right. This library main purpose is to format a number to a currency representation (e.g.: $15.00), it isn't intended for math or calculation purposes. 

Of course, if you have a suggestion or more specific details why float should not be used, feel free to share it. :smiley: 

Closing as I do not see a real issue here.
